language: node_js
sudo: required

jobs:
  include:
    - stage: Tests
      script:
        - npm run test:functional
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
