language: node_js
sudo: required
script:
  - npm run build
after_success:
  - '[[ $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" ]] &&
    (npm run travis-deploy-once "npm run semantic-release")'
